name: Automate the generation of meetings file

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: python3 -m pip install bs4 pytz pandas
    - name: Run scrapping script
      run: python3 ./src/data/yt_data_scrapping.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto update meetings.json
